In [1]:
import numpy as np

In [2]:
#creating 1D array
array1 = np.array([1,2,3,4])
print(array1)

[1 2 3 4]


In [3]:
#2D array
array2 = np.array([[1,2,3],[4,5,6]])
print(array2)

[[1 2 3]
 [4 5 6]]


In [4]:
#dimension/shape of array
print(array2.shape)

(2, 3)


In [5]:
#arrang() - generate numpy array

array1 = np.arange(0,10)
print(array1)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
#identity matrix

matrix = np.eye(2)
print(matrix)


[[1. 0.]
 [0. 1.]]


In [7]:
# generating random numbers - uniformly distributed in 0 & 1.
seed=101


In [8]:
rn1 = np.random.rand(5) 
print(rn1)


[0.75179326 0.02215711 0.48448761 0.2162263  0.65311427]


In [9]:
rn2 = np.random.randint(5) #returns only one random integer
print(rn2)


3


In [10]:
rn3 = np.random.randn(5) #samples from standard normal dist. with mean=0 and sd=1.
print(rn3)


[ 0.96354812 -0.76299905 -0.3675521  -0.89653616  0.22633645]


In [11]:
array1 = np.array([[1,2,3],[4,5,6]])


In [12]:
np.sqrt(array1)


array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [13]:
np.exp(array1)


array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [14]:
np.log(array1)


array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [15]:
np.std(array1)


1.707825127659933